baseURL = 'https://sven.eisenschmidr.website/'
languageCode = 'en-us'
title = 'sven.eisenschmidt.website'
theme = 'website'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'About Me'
    pageRef = '/about'
    weight = 99

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = 'Feed'
    url = '/index.xml'
    weight = 50
