baseURL = "https://sven.eisenschmidt.website/"
languageCode = "en-us"
title = "Sven Eisenschmidt"
theme = "website"

[params]
description = "Personal website of Sven Eisenschmidt, based in Leipzig, Germany."
author = "Sven Eisenschmidt"
keywords = "Sven Eisenschmidt, Leipzig, Germany, video games, music, cycling, travel, software development, photography"

[taxonomies]
topic = "topics"

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[caches.images]
dir = ":cacheDir/images"

[[menus.main]]
name = "Search"
pageRef = "/search"
weight = 10

[[menus.main]]
name = "Topics"
pageRef = "/topics"
weight = 30

[[menus.main]]
name = "Photos"
pageRef = "/photos"
weight = 35

[[menus.main]]
name = "Blogroll"
url = "/blogroll"
weight = 40

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 99
