baseURL = "https://sven.eisenschmidt.website/"
languageCode = "en-us"
title = "Sven Eisenschmidt - Personal Blog"


[pagination]
pagerSize = 10

[params]
description = "Personal website of Sven Eisenschmidt, based in Leipzig, Germany."
siteHeading = "Sven Eisenschmidt"
author = "Sven Eisenschmidt"
keywords = "Sven Eisenschmidt, Leipzig, Germany, video games, music, cycling, travel, software development, photography"
jobTitle = "Chief Technology & Product Officer"
employer = "roadsurfer"
employerUrl = "https://roadsurfer.com"
githubUrl = "https://github.com/sveneisenschmidt"
linkedinUrl = "https://linkedin.com/in/sveneisenschmidt"
stravaUrl = "https://strava.com/athletes/sveneisenschmidt"
email = "sven.eisenschmidt@gmail.com"

[taxonomies]
topic = "topics"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML"]
term = ["HTML"]

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
codeFences = true
noClasses = false
lineNos = false

[markup.goldmark.parser.attribute]
block = true
title = true

[caches.images]
dir = ":cacheDir/images"

[[menus.main]]
name = "Search"
pageRef = "/search"
weight = 10

[[menus.main]]
name = "Topics"
pageRef = "/topics"
weight = 30

[[menus.main]]
name = "Photos"
pageRef = "/photos"
weight = 35

[[menus.main]]
name = "Log"
pageRef = "/log"
weight = 37

[[menus.main]]
name = "Blogroll"
url = "/blogroll"
weight = 40

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 99
